# Generated by Django 3.1.5 on 2021-01-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('student', models.ManyToManyField(to='restapi.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentClass', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGroup', models.CharField(choices=[('A+', 'A(+ve)'), ('B+', 'B(+ve)'), ('O+', 'O(+ve)'), ('A-', 'A(-ve))'), ('B-', 'B(-ve)'), ('O-', 'O(-ve)'), ('AB+', 'AB(+ve)'), ('AB-', 'AB(-ve)')], max_length=3)),
                ('address', models.CharField(max_length=1000)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.student')),
            ],
        ),
    ]
